package com.docplexus.token.orm;
// Generated 12 Jul, 2018 4:24:16 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "bank", catalog = "tokenMgt")
public class Bank implements java.io.Serializable {

	private Long id;
	private String name;
	private Set<Banker> bankers = new HashSet<Banker>(0);
	private Set<Branch> branches = new HashSet<Branch>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Bank() {
	}

	public Bank(String name, Set<Banker> bankers, Set<Branch> branches, Set<Customer> customers) {
		this.name = name;
		this.bankers = bankers;
		this.branches = branches;
		this.customers = customers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bank")
	public Set<Banker> getBankers() {
		return this.bankers;
	}

	public void setBankers(Set<Banker> bankers) {
		this.bankers = bankers;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bank")
	public Set<Branch> getBranches() {
		return this.branches;
	}

	public void setBranches(Set<Branch> branches) {
		this.branches = branches;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bank")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
