package com.docplexus.token.orm;
// Generated Jul 15, 2018 1:29:22 PM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "tokenmgt")
public class Customer implements java.io.Serializable {

	private Long id;
	private Bank bank;
	private String name;
	private Boolean previladged;

	public Customer() {
	}

	public Customer(Bank bank, String name, Boolean previladged) {
		this.bank = bank;
		this.name = name;
		this.previladged = previladged;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bankId")
	public Bank getBank() {
		return this.bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "previladged")
	public Boolean getPreviladged() {
		return this.previladged;
	}

	public void setPreviladged(Boolean previladged) {
		this.previladged = previladged;
	}

}
